fix(hypr): hyprland setup and config issues

diff --git a/bin/setup-dist/arch/setup b/bin/setup-dist/arch/setup
--- a/bin/setup-dist/arch/setup
+++ b/bin/setup-dist/arch/setup
@@ -18,10 +18,16 @@ function configure_hyprland {
   # Hyprland + utils
   sudo pacman -S --needed --noconfirm hyprland hyprlock hypridle hyprshutdown hyprsunset hyprpolkitagent \
     sddm pipewire pipewire-audio pipewire-pulse wireplumber xdg-desktop-portal xdg-desktop-portal-hyprland \
-    udiskie brightnessctl pamixer waybar blueman bluez dunst libnotify wl-clipboard \
-    swaybg starship rofi yazi gnome-calendar grim slurp swappy htop nvtop pavucontrol \
-    qt5-wayland qt6-wayland qt5ct qt6ct kvantum-qt5 kvantum adw-gtk-theme otf-codenewroman-nerd
-  
+    udiskie brightnessctl pamixer playerctl waybar blueman bluez dunst libnotify wl-clipboard \
+    swaybg starship rofi yazi kitty fish gnome-calendar grim slurp swappy htop btop nvtop pavucontrol \
+    networkmanager nm-connection-editor unzip \
+    qt5-wayland qt6-wayland qt5ct qt6ct kvantum-qt5 kvantum nwg-look adw-gtk-theme papirus-icon-theme \
+    otf-codenewroman-nerd
+
+  if ! command -v yay > /dev/null; then
+    log_error "yay is required to install AUR packages (wlogout, librewolf-bin). Install it and re-run."
+    return 1
+  fi
   yay -S --needed wlogout librewolf-bin
 
   # hyprpm deps
@@ -33,19 +39,24 @@ function configure_hyprland {
   sudo sed -i -e 's/^\#AutoEnable=true/AutoEnable=false/' /etc/bluetooth/main.conf
   sudo systemctl enable bluetooth --now
 
+  # Not --now, starting it would take over the current TTY
+  sudo systemctl enable sddm
+
   cursor_version=$(get_latest_release "catppuccin/cursors")
   curl -fsSL "https://github.com/catppuccin/cursors/releases/download/$cursor_version/catppuccin-latte-red-cursors.zip" \
     -o /tmp/catppuccin-latte-red-cursors.zip
   unzip -o /tmp/catppuccin-latte-red-cursors.zip -d "$HOME/.local/share/icons/"
 
   rsync -av "$ROOT/dotfiles/.config/mimeapps.list"      "$HOME/.config/mimeapps.list"
-  ln -s ~/.config/mimeapps.list ~/.local/share/applications/mimeapps.list
+  mkdir -p "$HOME/.local/share/applications"
+  ln -sfn "$HOME/.config/mimeapps.list" "$HOME/.local/share/applications/mimeapps.list"
 
   rsync -av "$ROOT/dotfiles/.config/starship.toml"      "$HOME/.config/starship.toml"
 
   rsync -av "$ROOT/images/wallpapers/nord_scenary.png"  "$HOME/.cache/current-wallpaper"
   rsync -av --delete "$ROOT/images/wallpapers/"         "$HOME/Pictures/wallpapers/"
   rsync -av --delete "$ROOT/images/profile-pictures/"   "$HOME/Pictures/profile-pictures/"
+  mkdir -p "$HOME/Pictures/screenshots"  # Used by the screenshot keybinds and swappy
 
   rsync -av --delete "$ROOT/dotfiles/.config/wal/"      "$HOME/.cache/wal/"
 
